'use client';
import type { ProgramDomain, ProgramSubtag } from '@fp/shared';

interface IconProps {
  size?: number;
  className?: string;
}

// ── Color system ───────────────────────────────────────────────────────────────
// Maps each subtag to its domain color. CSS variables must exist in globals.css.

const SUBTAG_DOMAIN: Record<ProgramSubtag, 'AIR' | 'SEA' | 'EXP' | 'SPACE_CYBER' | 'CROSS'> = {
  Fighter:    'AIR',
  Bomber:     'AIR',
  Transport:  'AIR',
  Carrier:    'SEA',
  Sub:        'SEA',
  Surface:    'SEA',
  Capital:    'SEA',
  Marine:     'EXP',
  SOF:        'EXP',
  Ops:        'EXP',
  Space:      'SPACE_CYBER',
  Cyber:      'SPACE_CYBER',
  Network:    'SPACE_CYBER',
  Classified: 'SPACE_CYBER',
  Industry:   'CROSS',
  Doctrine:   'CROSS',
  Politics:   'CROSS',
};

const DOMAIN_COLOR_VAR: Record<string, string> = {
  AIR:         'var(--color-domain-air)',
  SEA:         'var(--color-domain-sea)',
  EXP:         'var(--color-domain-exp)',
  SPACE_CYBER: 'var(--color-domain-space-cyber)',
  CROSS:       'var(--color-si)',
};

/** Returns the domain color CSS value for a given subtag. */
export function subtagColor(subtag: ProgramSubtag): string {
  return DOMAIN_COLOR_VAR[SUBTAG_DOMAIN[subtag]] ?? 'currentColor';
}

// ── Icon content (generated by scripts/generate-icons.ts) ─────────────────────
// To regenerate: npx tsx scripts/generate-icons.ts
// To regenerate specific icons: npx tsx scripts/generate-icons.ts --resume --only Fighter,Sub

const SUBTAG_CONTENT: Record<ProgramSubtag, () => React.ReactElement> = {
  Fighter: () => (
    <>
      <path fill="currentColor" d="M10 2l-6 12h2l4-2 4 2h2l-6-12zM8 15v3h1v-3zM11 15v3h1v-3z"/>
    </>
  ),
  Bomber: () => (
    <>
      <path fill="currentColor" d="M2 10l8-3 8 3-2 6-6-2-6 2-2-6z"/>
    </>
  ),
  Transport: () => (
    <>
      <path fill="currentColor" d="M8 2h4v16H8V2zM2 7h16v4H2V7z"/>
    </>
  ),
  Carrier: () => (
    <>
      <path fill="currentColor" d="M2,8l3-1h14v7h-17L2,8z"/>
      <rect fill="currentColor" x="13" y="5" width="4" height="2"/>
    </>
  ),
  Sub: () => (
    <>
      <path fill="currentColor" d="M2,10c0-2,2-3,6-3h8c2,0,3,1,3,3c0,2-1,3-3,3H8c-4,0-6-1-6-3z"/>
      <rect fill="currentColor" x="9" y="5" width="3" height="3"/>
      <path fill="currentColor" d="M18,10l2,2v-1l-2-2z"/>
    </>
  ),
  Surface: () => (
    <>
      <path d="M2 14h16v2c0 2-2 2-2 2H4c0 0-2 0-2-2v-2z" fill="currentColor"/>
      <path d="M3 13l2-2h11l2 2H3z" fill="currentColor"/>
      <path d="M9 8h4v3H9z" fill="currentColor"/>
      <path d="M10 6h2v2h-2z" fill="currentColor"/>
      <circle cx="5" cy="11" r="1.5" fill="currentColor"/>
    </>
  ),
  Capital: () => (
    <>
      <path fill="currentColor" d="M2 14h16l-1 3H3l-1-3zM5 11h3v2H5v-2zm5 0h3v2h-3v-2zm-1-3h5v2h-5V8zM8 7h4v1H8V7z"/>
    </>
  ),
  Marine: () => (
    <>
      <path fill="currentColor" d="M3 9a7 7 0 0 1 14 0H3z"/>
      <path fill="currentColor" d="M10 11l-3 6h6l-3-6z"/>
      <circle fill="currentColor" cx="10" cy="17" r="2"/>
      <path fill="currentColor" d="M8 10l-2 3M12 10l2 3" stroke="currentColor" strokeWidth="2"/>
    </>
  ),
  SOF: () => (
    <>
      <path fillRule="evenodd" fill="currentColor" d="M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14Zm0 2a5 5 0 1 0 0 10 5 5 0 0 0 0-10Z"/>
      <rect x="9" y="1" width="2" height="2" fill="currentColor"/>
      <rect x="9" y="17" width="2" height="2" fill="currentColor"/>
      <rect x="1" y="9" width="2" height="2" fill="currentColor"/>
      <rect x="17" y="9" width="2" height="2" fill="currentColor"/>
    </>
  ),
  Ops: () => (
    <>
      <path fillRule="evenodd" fill="currentColor" d="M10 2a8 8 0 1 0 0 16 8 8 0 0 0 0-16zm0 2a6 6 0 1 0 0 12 6 6 0 0 0 0-12z"/>
      <rect x="9" y="0" width="2" height="3" fill="currentColor"/>
      <rect x="9" y="17" width="2" height="3" fill="currentColor"/>
      <rect x="0" y="9" width="3" height="2" fill="currentColor"/>
      <rect x="17" y="9" width="3" height="2" fill="currentColor"/>
      <circle cx="10" cy="10" r="1.5" fill="currentColor"/>
    </>
  ),
  Space: () => (
    <>
      <rect x="7" y="9" width="6" height="5" fill="currentColor"/>
      <rect x="2" y="10" width="4" height="3" fill="currentColor"/>
      <rect x="14" y="10" width="4" height="3" fill="currentColor"/>
      <rect x="9.5" y="6" width="1" height="3" fill="currentColor"/>
      <circle cx="10" cy="5" r="1.5" fill="currentColor"/>
    </>
  ),
  Cyber: () => (
    <>
      <path fillRule="evenodd" fill="currentColor" d="M10 2L2 6v5c0 5.5 8 7 8 7s8-1.5 8-7V6L10 2zm0 6a2 2 0 0 0-2 2v2h4v-2a2 2 0 0 0-2-2zM9 7V6a1 1 0 1 1 2 0v1h-2z"/>
    </>
  ),
  Network: () => (
    <>
      <circle cx="10" cy="4" r="3" fill="currentColor"/>
      <circle cx="4" cy="16" r="3" fill="currentColor"/>
      <circle cx="16" cy="16" r="3" fill="currentColor"/>
      <path fill="currentColor" d="M11.5 5.5L16 14.5L14 15.5L9.5 6.5z"/>
      <path fill="currentColor" d="M8.5 5.5L4 14.5L6 15.5L10.5 6.5z"/>
      <rect x="5" y="15" width="10" height="2" fill="currentColor"/>
    </>
  ),
  Classified: () => (
    <>
      <path fillRule="evenodd" fill="currentColor" d="M19,10 C19,14.42 14.97,18 10,18 C5.03,18 1,14.42 1,10 C1,5.58 5.03,2 10,2 C14.97,2 19,5.58 19,10 Z M10,3 C5.58,3 2,6.13 2,10 C2,13.87 5.58,17 10,17 C14.42,17 18,13.87 18,10 C18,6.13 14.42,3 10,3 Z"/>
      <path fill="currentColor" d="M2.5,18.5 L18.5,2.5 L17.5,1.5 L1.5,17.5 Z"/>
    </>
  ),
  Industry: () => (
    <>
      <path fillRule="evenodd" fill="currentColor" d="M10 2l1.5 2.5h3l-1.5 2.5 1.5 2.5h-3l1.5 2.5-1.5 2.5-2.5-1.5-2.5 1.5-1.5-2.5 2.5-1.5-1.5-2.5 3-2.5-1.5-2.5h3zm0 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8zM10 7a3 3 0 1 0 0 6 3 3 0 0 0 0-6z"/>
    </>
  ),
  Doctrine: () => (
    <>
      <path fill="currentColor" d="M10 3l8 2v12l-8-2V3zM10 3l-8 2v12l8-2V3z"/>
    </>
  ),
  Politics: () => (
    <>
      <path fill="currentColor" d="M0,8h5c0,0,1,0,1,1s0,2,0,2l-2,2l-4,-1l0,-3z"/>
      <path fill="currentColor" d="M20,8h-5c0,0,-1,0,-1,1s0,2,0,2l2,2l4,-1l0,-3z"/>
      <path fill="currentColor" d="M6,7l3,2l-1,3l-3,-2z"/>
      <path fill="currentColor" d="M14,7l-3,2l1,3l3,-2z"/>
      <path fill="currentColor" d="M9,9l2,0l0,2l-2,0z"/>
    </>
  ),
};

const DOMAIN_CONTENT: Record<ProgramDomain, () => React.ReactElement> = {
  AIR: () => (
    <>
      <path fill="currentColor" d="M10 3L2 13h3l5-6 5 6h3L10 3z"/>
      <path fill="currentColor" d="M5 16l5-6 5 6H5z"/>
    </>
  ),
  SEA: () => (
    <>
      <path fill="currentColor" d="M2,5c3,0,5,2,8,2s5-2,8-2v2c-3,0-5,2-8,2s-5-2-8-2V5z"/>
      <path fill="currentColor" d="M2,10c3,0,5,2,8,2s5-2,8-2v2c-3,0-5,2-8,2s-5-2-8-2v-2z"/>
      <path fill="currentColor" d="M2,15c3,0,5,2,8,2s5-2,8-2v2c-3,0-5,2-8,2s-5-2-8-2v-2z"/>
    </>
  ),
  EXP: () => (
    <>
      <path fill="currentColor" d="M10 2l2.4 5.2h5.6l-4.4 3.8 1.6 5.4-4.8-3.4-4.8 3.4 1.6-5.4-4.4-3.8h5.6z"/>
    </>
  ),
  SPACE_CYBER: () => (
    <>
      <path fillRule="evenodd" fill="currentColor" d="M10 20C4.477 20 0 15.523 0 10S4.477 0 10 0s10 4.477 10 10-4.477 10-10 10zm0-3c3.866 0 7-3.134 7-7s-3.134-7-7-7-7 3.134-7 7 3.134 7 7 7zM10 13a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
      <path fill="currentColor" d="M2.5 10a12.5 4.5 0 0 1 15 0 12.5 4.5 0 0 1-15 0z" transform="rotate(-30 10 10)"/>
      <path fill="currentColor" d="M2.5 10a12.5 4.5 0 0 1 15 0 12.5 4.5 0 0 1-15 0z" transform="rotate(30 10 10)"/>
    </>
  ),
};

// ── Public components ──────────────────────────────────────────────────────────

export function SubtagIcon({
  subtag,
  size = 14,
  className,
  colored = false,
}: { subtag: ProgramSubtag; colored?: boolean } & IconProps) {
  const render = SUBTAG_CONTENT[subtag];
  if (!render) return null;
  const color = colored ? subtagColor(subtag) : 'currentColor';
  return (
    <svg
      viewBox="0 0 20 20"
      width={size}
      height={size}
      fill={color}
      style={colored ? { color } : undefined}
      className={className}
      aria-hidden="true"
    >
      {render()}
    </svg>
  );
}

export function DomainIcon({
  domain,
  size = 14,
  className,
  colored = false,
}: { domain: ProgramDomain; colored?: boolean } & IconProps) {
  const render = DOMAIN_CONTENT[domain];
  if (!render) return null;
  const color = colored ? (DOMAIN_COLOR_VAR[domain] ?? 'currentColor') : 'currentColor';
  return (
    <svg
      viewBox="0 0 20 20"
      width={size}
      height={size}
      fill={color}
      style={colored ? { color } : undefined}
      className={className}
      aria-hidden="true"
    >
      {render()}
    </svg>
  );
}
